### ISSUE TITLE
Update project to use build tools similar to Vanilla Framework

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/maas-gui-vanilla-theme#8]
Currently the MAAS GUI theme isn't an npm package or using the same tools as per vanilla framework.
### Tasks
- [ ] Setup Travis build process 
- [x] Create the theme to be a npm module
- [ ] Create release notes 
- [x] Update gulp build tools
